name: ci

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'     
        required: true


jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    steps:
      - name: step 1
        run: |
          echo "works"
