name: 'workflow'
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: mock up request message
        run: |
          echo 'VERSION=${{ env.COMMIT_REF }}' >> $GITHUB_ENV
        env:
          # if it's the release of schematic, get release versioning, otherwise, get commit sha
          COMMIT_REF: 'blabla'

      - name: create the branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'develop-update-schematic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          valueFile: test.yaml
          propertyPath: version.schematic
          value: ${{ env.VERSION }}
          branch: develop-update-schematic
          targetBranch: main
          createPR: true
          labels: dependencies
          description: blabla
          message: Auto update schematic for testing
          title: Version Updates
