name: ci

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'which instance site would your like to manually re-deploy?'    
        required: true
        type: choice
        options:
          - staging


jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    steps:
      - name: step 1
        run: |
          echo "${{ github.event.inputs.site }}"


