name: ci

on:
  push:
    branches: main
    tags: v*.*.*
  workflow_dispatch:
    inputs:
      service_branch:
        description: 'Schematic Service Branch (default is "develop")'    
        default: 'develop22'
      schema_branch:
        description: 'Schema Branch (default is "main")'    
        default: 'main22'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
      SERVICE_BRANCH: 'develop'
      SCHEMA_BRANCH: 'main'

    steps:
      - name: Determine deployment environment variables (manual)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          echo 'SERVICE_BRANCH=${{ github.event.inputs.service_branch }}' >> $GITHUB_ENV
          echo 'SCHEMA_BRANCH=${{ github.event.inputs.schema_branch }}' >> $GITHUB_ENV
          echo 'APP_URL=staging' >> $GITHUB_ENV
    
      - name: Determine deployment environment variables (pull request)
        if: github.event_name == 'pull_request'
        run: echo 'APP_URL=testing1' >> $GITHUB_ENV

      - name: Determine deployment environment variables (push)
        if: github.event_name == 'push'
        run: |
          echo "$GITHUB_REF"
          REF_NAME="$(echo $GITHUB_REF | cut -d'/' -f 3)"
          echo $REF_NAME
          if [[ "$REF_NAME" =~ ^v\([0-9]+\.\){2}[0-9]+ ]]; then
            echo 'APP_URL=production' >> $GITHUB_ENV
          else
            echo 'APP_URL=staging' >> $GITHUB_ENV
          fi

      - name: step2
        run: |
          echo "${{ env.SERVICE_BRANCH }}"
          echo "${{ env.SCHEMA_BRANCH }}"
          echo "${{ env.APP_URL }}"



