name: ci

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'which instance site would your like to manually re-deploy?'    
        required: true
        type: choice
        options:
          - staging
          - release


jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    steps:
      - name: Determine deployment sites
        run: |
          if ${{ github.event.inputs.site == 'staging'}}
          then
            echo 'SITE=staging' >> $GITHUB_ENV
          else
            echo 'SITE=release' >> $GITHUB_ENV
          fi

      - name: step2
        if: ${{ github.ref == "develop" && env.SITE == 'staging' }}
        run: |
          echo '${{ github.ref }}'
          echo 'staing-yes'




