name: ci

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      service_branch:
        description: 'Schematic Service Branch (default is "develop")'    
        default: 'develop22'
      schema_branch:
        description: 'Schema Branch (default is "main")'    
        default: 'main22'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    # steps:
    #   - name: Determine deployment environment variables
    #     run: |
    #       if ${{ github.event_name == 'workflow_dispatch'}}; then
    #         echo 'SERVICE_BRANCH=${{ github.event.inputs.service_branch }}' >> $GITHUB_ENV
    #         echo 'SCHEMA_BRANCH=${{ github.event.inputs.schema_branch }}' >> $GITHUB_ENV
    #         echo 'APP_URL=staging' >> $GITHUB_ENV
    #       else
    #         echo 'SERVICE_BRANCH=develop' >> $GITHUB_ENV
    #         echo 'SCHEMA_BRANCH=main' >> $GITHUB_ENV
    #         if [["v1.1.1" =~ '^v([0-9]+\.){2}[0-9]+$']]
    #         echo "REF_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    #       fi
  
    #       echo "REF_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    steps:
      - name: step2
        run: |
          if $(echo "v1.1.1" | grep "^v([0-9]+\.){2}[0-9]+$"); then
            echo "v1.1.1-yes"
          else
            echo "v1.1.1-no"
          fi




