name: ci

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      service_branch:
        description: 'Schematic Service Branch (default is "develop")'    
        default: 'develop22'
      schema_branch:
        description: 'Schema Branch (default is "main")'    
        default: 'main22'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # This image seems to be based on rocker/r-ver which in turn is based on debian
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    steps:
      - name: Determine deployment sites
        run: |
          if ${{ github.event_name == 'workflow_dispatch'}}; then
            echo 'SERVICE_BRANCH=${{ github.event.inputs.service_branch }}' >> $GITHUB_ENV
            echo 'SCHEMA_BRANCH=${{ github.event.inputs.schema_branch }}' >> $GITHUB_ENV
          else
            echo 'SERVICE_BRANCH=develop' >> $GITHUB_ENV
            echo 'SCHEMA_BRANCH=main' >> $GITHUB_ENV
          fi
  
          echo "REF_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: step2
        run: |
          echo "${{ github.event.inputs.SERVICE_BRANCH }}"
          echo "${{ github.event.inputs.SCHEMA_BRANCH }}"




